
spring:
  # Redis 配置
  redis:
    database: 0  #数据库索引(默认为0)
    host: 192.168.2.200
    port: 6379  #默认链接端口
    password:  123456
    lettuce:
      pool:
        max-active: 8 #最大链接池
        max-wait: -1 #最大阻赛等待时间（使用负值没有限制）默认为-1
        max-idle: 8 #连接池中的最大空闲连接 默认 8
        min-idle: 0
  main:
    ##注意 必须加上引号 不可能会出错
    banner-mode: "off"
server:
  port: 8090